apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fairgig-services
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - app
  selector:
    matchLabels:
      monitored: "true"
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: app                   
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod