apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fairgig-services
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - app
  selector:
    matchLabels:
      monitored: "true"    # add this label to all your app services
  endpoints:
    - port: http
      path: /metrics
      interval: 15s