apiVersion: v1
kind: Service
metadata:
  labels:
    monitored: "true"
  name: earnings-service
  namespace: app
spec:
  selector:
    app: earnings-service
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP