apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: app
type: Opaque
stringData:
  ENVIRONMENT: development
  PORT: 8000
  DATABASE_URL: postgresql+asyncpg://youruser:yourpassword@postgres:5432/fairgig_auth
  REDIS_URL: redis://redis:6379/0
  APP_NAME: FairGig Auth Service
  API_PREFIX: /api
  ACCESS_TOKEN_SECRET: change-access-token-secret
  REFRESH_TOKEN_SECRET: change-refresh-token-secret
  OTP_HASH_SECRET: change-otp-hash-secret
  JWT_ALGORITHM: HS256
  BREVO_API_KEY: ""
  BREVO_SENDER_EMAIL: no-reply@fairgig.app
  BREVO_SENDER_NAME: FairGig
  ALLOWED_CORS_ORIGINS: "[http://localhost:5173,http://localhost:8080]"