apiVersion: v1
kind: Secret
metadata:
  name: certificate-secrets
  namespace: app
type: Opaque
stringData:
  PORT: 8004
  API_PREFIX: /api/certificate
  JWT_SECRET: change-access-token-secret
  ACCESS_TOKEN_SECRET: change-access-token-secret
  JWT_ALGORITHM: HS256
  EARNINGS_SERVICE_URL: http://earnings-service:3001/api/earnings
  INTERNAL_SERVICE_API_KEY: fairgig-internal-dev-key
  REQUEST_TIMEOUT_SECONDS: 8
  TEMPLATE_DIR: app/templates
  CORS_ORIGINS: http://localhost:5173,http://localhost:8080