apiVersion: v1
kind: Secret
metadata:
  name: grievance-secrets
  namespace: app
type: Opaque
stringData:
  NODE_ENV: development
  PORT: 3002
  MONGO_URI: mongodb://mongodb-service:27017/fairgig_grievance
  JWT_SECRET: change-access-token-secret
  CORS_ORIGINS: http://localhost:5173,http://localhost:8080