apiVersion: v1
kind: Service
metadata:
  labels:
    monitored: "true"
  name: grievance-service
  namespace: app
spec:
  selector:
    app: grievance-service
  ports:
    - name: http
      port: 3002
      targetPort: 3002
  type: ClusterIP