apiVersion: v1
kind: Service
metadata:
  labels:
    monitored: "true"
  name: frontend-service
  namespace: app
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP