apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: sufyanliaqat/analytics-service:v1
          ports:
            - containerPort: 8003
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: analytics-secrets
                  key: DATABASE_URL
            - name: EARNINGS_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: analytics-secrets
                  key: EARNINGS_DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: analytics-secrets
                  key: JWT_SECRET
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: analytics-secrets
                  key: ACCESS_TOKEN_SECRET
            - name: JWT_ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: analytics-secrets
                  key: JWT_ALGORITHM
            - name: CACHE_TTL_SECONDS
              valueFrom:
                secretKeyRef:
                  name: analytics-secrets
                  key: CACHE_TTL_SECONDS
            - name: PLATFORMS_CACHE_TTL_SECONDS
              valueFrom:
                secretKeyRef:
                  name: analytics-secrets
                  key: PLATFORMS_CACHE_TTL_SECONDS
            - name: GRIEVANCE_CACHE_TTL_SECONDS
              valueFrom:
                secretKeyRef:
                  name: analytics-secrets
                  key: GRIEVANCE_CACHE_TTL_SECONDS
            - name: MIN_COHORT_SIZE
              valueFrom:
                secretKeyRef:
                  name: analytics-secrets
                  key: MIN_COHORT_SIZE
            - name: WORKER_REF_SALT
              valueFrom:
                secretKeyRef:
                  name: analytics-secrets
                  key: WORKER_REF_SALT
            - name: GRIEVANCE_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: analytics-secrets
                  key: GRIEVANCE_SERVICE_URL
            - name: GRIEVANCE_TIMEOUT_SECONDS
              valueFrom:
                secretKeyRef:
                  name: analytics-secrets
                  key: GRIEVANCE_TIMEOUT_SECONDS
            - name: CORS_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: analytics-secrets
                  key: CORS_ORIGINS
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 5