apiVersion: v1
kind: Service
metadata:
  labels:
    monitored: "true"
  name: analytics-service
  namespace: app
spec:
  selector:
    app: analytics-service
  ports:
    - port: 8003
      targetPort: 8003
  type: ClusterIP