apiVersion: apps/v1
kind: Deployment
metadata:
  name: certificate-service
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: certificate-service
  template:
    metadata:
      labels:
        app: certificate-service
    spec:
      containers:
        - name: certificate-service
          image: sufyanliaqat/certificate-service:v1
          ports:
            - containerPort: 8004
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: certificate-secrets
                  key: PORT
            - name: API_PREFIX
              valueFrom:
                secretKeyRef:
                  name: certificate-secrets
                  key: API_PREFIX
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: certificate-secrets
                  key: JWT_SECRET
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: certificate-secrets
                  key: ACCESS_TOKEN_SECRET
            - name: JWT_ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: certificate-secrets
                  key: JWT_ALGORITHM
            - name: EARNINGS_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: certificate-secrets
                  key: EARNINGS_SERVICE_URL
            - name: INTERNAL_SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: certificate-secrets
                  key: INTERNAL_SERVICE_API_KEY
            - name: REQUEST_TIMEOUT_SECONDS
              valueFrom:
                secretKeyRef:
                  name: certificate-secrets
                  key: REQUEST_TIMEOUT_SECONDS
            - name: TEMPLATE_DIR
              valueFrom:
                secretKeyRef:
                  name: certificate-secrets
                  key: TEMPLATE_DIR
            - name: CORS_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: certificate-secrets
                  key: CORS_ORIGINS
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 10
            periodSeconds: 5