apiVersion: v1
kind: Service
metadata:
  labels:
    monitored: "true"
  name: certificate-service
  namespace: app
spec:
  selector:
    app: certificate-service
  ports:
    - name: http
      port: 8004
      targetPort: 8004
  type: ClusterIP