apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: app
spec:
  selector:
    app: postgres
  ports:
    - name: http
      port: 5432
      targetPort: 5432
  type: ClusterIP