"""create analytics run logs table

Revision ID: 01b7be3e4dd5
Revises: 
Create Date: 2026-04-18 17:56:57.051914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b7be3e4dd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_run_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_run_logs_id'), 'analytics_run_logs', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_run_logs_metric'), 'analytics_run_logs', ['metric'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_run_logs_metric'), table_name='analytics_run_logs')
    op.drop_index(op.f('ix_analytics_run_logs_id'), table_name='analytics_run_logs')
    op.drop_table('analytics_run_logs')
    # ### end Alembic commands ###
